domainroot: http://v2.the-open.net
meta:
  title: The Online Progressive Engagement Network
  description:
    Our member organizations use a common model of member-led, large-scale campaigning to help a combined 15+ million supporters act together for the common good. OPEN exists to help this unique global family of national movements collaborate, share and grow. Join Us!
  fb_description:
    OPEN is a sisterhood of grassroots campaigning organizations from around the world. Our member organizations use a common model of member-led, large-scale campaigning to help a combined 15+ million supporters act together for the common good. OPEN exists to help this unique global family of national movements collaborate, share and grow.
  keywords: online progressive engagement network political
    non-party independent activism citizen empowermend social climate economic racial justice human rights feminism equality gender sexuality expression non-conforming people-powered grassroots digital petition protest vote volunteer donate
  fb_site_name: The OPEN
  fb_title: The Online Progressive Engagement Network

staff:
- name: Ben Brandzel
  title: Founder and Executive Director
  location: Bangalore, India
  email: ben@the-open.net
  description: 'After serving as MoveOn.org&rsquo;s original Advocacy Director from 2004-2006, Ben has become a significant global catalyst of progressive digital organizing. From 2007-2013 he personally helped found or lead every OPEN member organization and post-launch start-up, (with the exception of Campact). He came home to serve as Director of New Media Campaigns and Fundraising for President Barack Obama during the 2009-2010 health reform campaign. Ben was a founding Campaign Director at Avaaz where he still serves on the Board of Directors. From 2011-2012 he served as Strategy Director for the Citizen Engagement Lab, where he devised, tested and refined best practices for incubating and networking digital campaigning organizations. In 2013, he co-convened the OPEN Summit which led to OPEN&rsquo;s creation and has been living this dream ever since.'
- name: Phil Ireland
  title: Managing Director
  location: Sydney, Australia
  email: phil@the-open.net
  description: 'Phil is a campaigner, organiser and strategist with over 10 years of experience in some of the world&rsquo;s leading progressive organisations. Most recently, he led the ground-breaking election campaign for 38Degrees, OPEN member and largest membership organisation in the UK. Prior to this he worked as a senior advisor at Purpose on The Syria Campaign and Director of Operations at United Voice NSW, one of Australia&rsquo;s largest unions, where he managed the Union&rsquo;s communications, finance, advocacy, membership and administration. Phil also has extensive experience in the NGO sector having worked for a range of different Australian and global NGOs. Of note, Phil led Oxfam&rsquo;s advocacy engagement with Australia and the Pacific both domestically and in the United Nations climate change negotiations. He is currently the Vice Chair of the board of the Global Campaign for Climate Action and remains an advisor to several non-profit organisations. Phil holds a Ph.D. in international development and has authored several peer-reviewed academic articles, book chapters and articles in the public media.'
- name: Michael Snook
  title: Technology Director
  location: Brooklyn, New York
  email: snook@the-open.net
  description: 'Michael Snook is an organizer and technologist from Charlottesville, Virginia, USA, currently based out of Bangalore. His time in the political world has taken him from field organizing, to fundraising and speechwriting, to analytics and targeting, to tech administration, to software development. In 2009 Michael helped found BoldProgressives.org and later served as Chief Information Officer, directing a team of designers, developers, and data analysts to keep things running smoothly while building new organizing tools to bring innovative new tactics and strategies to life. He gets excited about space exploration, cognitive linguistics, and distributed leadership models.'
- name: Shilpa Mudiganti
  title: Director of Operations
  location: Bangalore, India
  email: shilpa@the-open.net
  description: 'Shilpa has 12 years of experience in Administration and Human Resource Management in private and non-profit sectors. Her experience in workplace systems design ranges from Fortune 500 corporates to the UNDP in Sierra Leone. She is passionate about deploying her skills in the social change sector.'
- name: Claire Hermann
  title: Director of Development and Storytelling
  location: Pittsboro, United States
  email: claire@the-open.net
  description: 'Claire is passionate about finding and telling stories that illustrate the power of individuals and organizations to create a more just and sustainable world. Prior to joining the OPEN team, Claire served as the first Communications Director at two US-based non-profits, creating and deploying narratives that won meaningful health justice victories in a conservative political climate, brought together diverse stakeholders in the movement for a just and sustainable food system, raised funds, and mobilize the grassroots. She holds a Masters degree in Mass Communications with a focus on social change.'
- name: Becky Jarvis
  title: Network Architect
  location: London, UK
  email: becky@the-open.net
  description: 'A South Wales native, Becky was one of 38Degrees&rsquo;s first staff members and has a strong track-record of mobilizing millions to take action on the issues they care about. She’s led on the strategy, planning and execution of some of 38Degrees biggest campaigns. She has a particular expertise in email and web engagement, strategic planning, public affairs, project management, event coordination, field campaigning and working with external stakeholders. Prior to joining the staff team at 38Degrees, she worked as Director of Policy and Communication in the family sector for a children’s charity.'
- name: Libby Lenkinski
  title: Development and Growth Advisor
  location: Brooklyn, New York
  email: libby@the-open.net
  description: 'Libby directs strategy at the New Israel Fund, and previously worked with leading human rights organizations in Israel and Palestine. She has led outreach and engagement campaigns for documentary films and media outfits as well as social change initiatives. Libby is an advisor for +972 Magazine, an online magazine that brings progressive voices from Israel and Palestine and serves on the Board of Comet-ME, an organization that provides renewable energy systems to off-the-grid Palestinian communities in the West Bank.'
- name: Ranjani Rajashekaran
  title: Finance Manager
  location: Bangalore, India
  email: ranjani@the-open.net
  description: 'Ranjani has a Master&rsquo;s Degree in Accounting with 9 years of experience in diverse fields like accounting and finance, supply chain, advertising and operations. While most of her experience comes from the corporate sector, she is very enthusiastic about being associated with OPEN and contributing meaningfully to society.'
- name: Prameeta Pankaj Bajaj
  title: Executive Assistant to ED and MD
  location: Bangalore, India
  email: prameeta@the-open.net
  description: 'Prameeta has more than 15 years of work experience in Customer Service, Learning and Development, and Administration functions. She is an expert in administration with a demonstrated ability to multi-task, be proactive and partner with executives to increase their efficiency. She is fondly called the &ldquo;Bundle of Administrative Talent&rdquo; by her former colleagues.'

orgs:
- slug: leadnow
  code: CAN
  code2: ca
  founded:
  url: http://www.leadnow.ca/
  logo: /static/img/leadnow.png
  coordinates: '[-123.1207, 49.2827]'
  title: Leadnow
  description: '<a target="_blank" href="http://www.leadnow.ca/">Leadnow.ca</a> is Canada&rsquo;s leading online progressive advocacy group, with over 500,000 members. Founded in 2011 and focusing heavily on local leadership development, they have quickly become one of the most powerful voices on the left. In 2015 they ran the country&rsquo;s largest and most successful strategic voting campaign to defeat Stephen Harper.'
  category: core
- slug: moveon
  code: USA
  code2: us
  founded:
  url: http://www.moveon.org/
  logo: /static/img/moveon.svg
  coordinates: '[-98.5, 39.8]'
  title: MoveOn
  description: '<a target="_blank" href="http://www.moveon.org/">MoveOn.org</a> is the oldest and largest of the groups in the OPEN network. Founded in 1998, and with over 8 million members, they are the flagship organization among the robust American ecosystem of online, independent left organizations in America. MoveOn was one of the leading voices in opposing the Iraq war, passing ObamaCare, and stopping a senseless war with Iran.'
  category: core
- slug: 38degrees
  code: GBR
  code2: gb
  founded:
  url: http://38degrees.org.uk/
  logo: /static/img/38degrees.png
  coordinates: '[-0.12775, 51.50735]'
  title: 38 Degrees
  description: '<a target="_blank" href="http://38degrees.org.uk/">38Degrees.org.uk</a> is the largest OPEN organization per capita, with over 12% of the UK&rsquo;s voting population in their membership. They focus heavily on their distributed campaigns platform, CampaignsByYou, which has proven effective at elevating citizen voices to fight austerity at the local level, saving dozens of hospitals and libraries, while building a new model for local campaigning.'
  category: core
- slug: campact
  code: DEU
  code2: de
  founded:
  url: http://campact.de/
  logo: /static/img/campact.png
  coordinates: '[13.40495, 52.52]'
  title: Campact
  description: '<a target="_blank" href="http://campact.de/">Campact.de</a> was the first organisation in the network to begin without any contact with the others, only linking up in 2013 when OPEN was founded. Though they are a multi-issue organisation like all the rest, they focus heavily on anti-coal, anti-nuclear, anti-GMO campaigns, which has led them to become one of Europe&rsquo;s leading voices against bad trade deals, and a key part of coordinating transnational campaigns.'
  category: core
- slug: getup
  code: AUS
  code2: au
  founded:
  url: http://getup.org.au/
  logo: /static/img/getup.png
  coordinates: '[149.12868, -35.28199]'
  title: GetUp
  description: '<a target="_blank" href="http://getup.org.au/">GetUp.org.au</a> is known for taking on big fights and training some of the world&rsquo;s best online campaigners. Having just celebrated their 10th anniversary, GetUp marshalls over one million members to fight one of the world&rsquo;s most destructive coal-mining projects, end for-profit detention centers for assylum-seekers, and campaign for economic justice.'
  category: core
- slug: actionstation
  code: NZL
  code2: nz
  founded:
  url: http://actionstation.org.nz/
  logo: /static/img/actionstation.png
  coordinates: '[174.77623, -41.28646]'
  title: ActionStation
  description: '<a target="_blank" href="http://actionstation.org.nz/">ActionStation.org.nz</a> has over 100,000 Kiwis working for social justice, human rights, and climate justice in Aotearoa. Recent highlights include campaigning against the TPPA (another bad trade deal), and for the government to address sexual violence as a serious problem facing the country.'
  category: startup
- slug: uplift
  code: IRL
  code2: ie
  founded:
  url: http://uplift.ie/
  logo: /static/img/uplift.png
  coordinates: '[-6.2603, 53.3498]'
  title: Uplift
  description: '<a target="_blank" href="http://uplift.ie/">Uplift.ie</a>&rsquo;s 80,000 members work for progressive change in Ireland. Recently they have stood up for refugees, for the Irish fishing industry, against fracking and privatising water supplies.'
  category: startup
- slug: operationlibero
  code: CHE
  code2: ch
  founded:
  url: http://www.operation-libero.ch/
  logo: /static/img/operationlibero.jpg
  coordinates: '[7.44744, 46.94797]'
  title: Operation Libero
  description: '<a target="_blank" href="http://www.operation-libero.ch/">Operation-Libero.ch</a> is a startup, just about a year old. Because Swiss politics centers so much around constitutional referrenda, their approach is inherently social, making civic engagement compelling and fun for a new generation of voices who want create more inclusive, forward-thinking Switzerland.'
  category: startup
- slug: akcjademokracja
  code: POL
  code2: pl
  founded:
  url: http://www.akcjademokracja.pl/
  logo: /static/img/akcjademokracja.png
  coordinates: '[21.01222, 52.22967]'
  title: Akcja Demokracja
  description: '<a target="_blank" href="http://www.akcjademokracja.pl/">AkcjaDemokracja.pl</a> launched in Fall of 2015, just before Poland erupted into protests against government corruption, and saw a new right-wing government sweep into power. They&rsquo;ve already seen viral growth on some of their campaigns, and have been at the center of important fights to defend democracy, combat air pollution, and support working families.'
  category: startup
- slug: declic
  code: ROU
  code2: ro
  founded:
  url: http://www.de-clic.ro/
  logo: /static/img/declic.png
  coordinates: '[26.10253, 44.42676]'
  title: de-clic
  description: '<a target="_blank" href="http://www.de-clic.ro/">de-clic.ro</a> emerged from the leadership of a powerful and successful campaign to protect parks and watersheds from dangerous mining and logging projects. Now, as a multi-issue organisation, they are a crucial part of a small but growing civil society sector in one of Europe&rsquo;s youngest democracies.'
  category: startup
- slug: amandla
  code: ZAF
  code2: za
  founded:
  url: http://www.amandla.mobi/
  logo: /static/img/amandla.png
  coordinates: '[28.0473,-26.2041]'
  title: amandla.mobi
  description: '<a target="_blank" href="http://www.amandla.mobi/">Amandla.mobi</a> works to empower South Africa&rsquo;s most marginalized communities, especially black women from rural areas, by turning every cell phone into a tool for democracy. Though they face challenges many of the organizers in the network would never imagine, they manage to run inspiring campaigns against state violence and for the rights of workers and students, they do it in four languages on both web and mobile platforms, and they win!'
  category: startup
- slug: skiftet
  code: SWE
  code2: se
  founded:
  url: http://www.skiftet.org/
  logo: /static/img/skiftet.svg
  coordinates: '[18.06858, 59.32932]'
  title: Skiftet
  description: '<a target="_blank" href="http://www.skiftet.org/">Skiftet.org</a> is just over a year old, but already they count over 3% of the electorate in their membership. Having formed out of the leadership of a lefty blogging outfit, their tone tends toward the irreverent, but their campaigns are serious, taking on Monsanto, climate change, human rights, and equity in the education system.'
  category: startup
- slug: aufstehn
  code: AUT
  code2: at
  founded:
  url: http://www.aufstehn.at/
  logo: /static/img/aufstehn.png
  coordinates: '[16.37381, 48.20817]'
  title: '#aufstehn'
  description: '<a target="_blank" href="http://www.aufstehn.at/">Aufstehn.at</a> was founded in 2015 and dove straight into the refugee crisis with an inspiring, award-winning campaign to show local support welcoming refugees in cities and townships across the country.'
  category: startup
- slug: progressi
  code: ITA
  code2: it
  founded:
  url: http://www.progressi.org/
  logo: /static/img/progressi.png
  coordinates: '[12.48022, 41.87241]'
  title: Progressi
  description: '<a target="_blank" href="http://www.progressi.org/">Progressi.org</a> launched in fall of 2015 with campaigns in support of refugees, for civil marriage equality, and against climate change. They have already launched a distributed campaigns platform, opting for a role more as a steward of citizen campaigns, like <em>38 Degrees</em> and <em>Skiftet</em>, and plan to focus heavily on local leadership development like <em>Leadnow</em>.'
  category: startup
- slug: zazim
  code: ISR
  code2: il
  founded:
  url: http://www.zazim.org.il/
  logo: /static/img/zazim.png
  coordinates: '[35.2137, 31.76831]'
  title: Zazim
  description: '<a target="_blank" href="http://www.zazim.org.il/">Zazim.org.il</a> launched in the final days of 2015 with a campaign against new anti-muslim educational policies and textbooks. They operate in Hebrew and Arabic, and while Zazim is a multi-issue organisation, they understand that systemic racism and the occupation play a central roll in skewing or derailing nearly every other political debate in the country, and work to combat these problems in every campaign they run.'
  category: startup


exclude:
 - CNAME
 - .sass-cache
 - static/img/originals
 - scss
 - .git
