title: The Online Progressive Engagement Network
description:
  Our member organizations use a common model of member-led, large-scale campaigning to help a combined 15+ million supporters act together for the common good. OPEN exists to help this unique global family of national movements collaborate, share and grow. Join Us!
fb_description:
  OPEN is a sisterhood of grassroots campaigning organizations from around the world. Our member organizations use a common model of member-led, large-scale campaigning to help a combined 15+ million supporters act together for the common good. OPEN exists to help this unique global family of national movements collaborate, share and grow.
keywords: online progressive engagement network political
  non-party independent activism citizen empowermend social climate economic racial justice human rights feminism equality gender sexuality expression non-conforming people-powered grassroots digital petition protest vote volunteer donate
fb_site_name: The OPEN
fb_title: The Online Progressive Engagement Network
